### ISSUE TITLE
how to work with buttercup

### ISSUE THREAD

**Issue by xcodebuild** [undercover-el/undercover.el#14]
[`buttercup`](https://github.com/jorgenschaefer/emacs-buttercup) is a cool library for testing emacs-lisp.Could `undercover` work with it?

See more at https://github.com/jorgenschaefer/emacs-buttercup/issues/9

**Comment by sviridov** [comment]
I believe it should work. I can investigate it a bit later.
Should I try to add code coverage reports to `emacs-buttercup` itself or to some other project that uses it?

**Comment by CodeFalling** [comment]
It would be very nice to add code coverage reports to emacs-buttercup itself. :+1:

**Comment by sviridov** [comment]
Oh, I guess my English failed me...

I mean to add code coverage reports not **to** `emacs-butter` but **for** `emacs-butter`. Just to see `emacs-butter` coverage on it's project page.

But you mean to integrate `emacs-butter` and `undercover` to use it together automatically. Am I right? Something like this?

```bash
$ UNDERCOVER=true emacs -batch -f package-initialize -f buttercup-run-discover
```

**Comment by CodeFalling** [comment]
Yeah I just mean integrate with `buttercup`.Sorry I just misunderstand your reply because buttercup is just test in bettercup itself.

**Comment by sviridov** [comment]
So I want to start with something simple (before proposing any changes to `emacs-buttercup`) and I did some experiments with covering your `blog-admin`. It looks like `emacs-buttercup` and `undercover` works fine together but the issue that you faced [here](jorgenschaefer/emacs-buttercup#9) is actually related to `edebug` (`undercover` heavly relies on it) and `names` packages.

So here is my plan:
1. I will provide some basic `emacs-buttercup` and `undercover` usage examples, something like [this](https://github.com/sviridov/undercover.el-usage-example).
2. I will investigate issue with `names` package and will help you to cover `blog-admin`.
3. I will do some proposal to `emacs-buttercup` to automatically run `undercover` with it.

Please do not expect it soon because I'm very busy with my main work.

**Comment by CodeFalling** [comment]
Sounds great, take your time of course！

**Comment by sviridov** [comment]
I did few examples of `buttercup` usage together with `undercover`:

https://github.com/sviridov/undercover.el-buttercup-integration-example
https://github.com/sviridov/undercover.el-combined-usage-example

**Comment by CodeFalling** [comment]
Thanks for your awesome work! :+1:

**Comment by jorgenschaefer** [comment]
Author of Buttercup here - thank you very much for your work!

**Comment by cpitclaudel** [comment]
@sviridov Thanks for the examples, but they didn't work for me at first; I did figure it out after a long while of debugging, but maybe it would be useful to highlight in one of the examples that the libraries shouldn't be compiled?

Even better, it would be nice if undercover could complain if no files at all have been tested after a full run. Something like this maybe?

```
Undercover: No tests seem to have run. Make sure that your files are not compiled?
```

**Comment by DamienCassou** [comment]
I don't understand what this is about. `buttercup` and `undercover` work great together already without requiring anything special. For example : https://github.com/DamienCassou/klassified.el/pull/7.

**Comment by cpitclaudel** [comment]
@DamienCassou This discussion is a year old :/ Could it be that things got better?
The trouble I did run into at the time was that I was running compiled code, and instrumentation didn't work there, IIRC.

**Comment by DamienCassou** [comment]
Clément Pit-Claudel <notifications@github.com> writes:
> @DamienCassou This discussion is a year old :/ Could it be that 
> things got better?


possibly


> The trouble I did run into at the time was that I was running 
> compiled code, and instrumentation didn't work there, IIRC. 


that's still the case: you can't instrument compiled code. 

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by CyberShadow** [comment]
> that's still the case: you can't instrument compiled code.

`edebug` has no chance to work with compiled bytecode, as (AFAIU) it does not contain sufficient information to reliably map the bytecode to source line numbers. For this reason, undercover can't work with compiled files either.

It seems to me that there remain no actionables in this issue, so, closing. If there is anything missing, please add a comment and we can reopen, or create a new issue.
