### ISSUE TITLE
Generalize support for CI services (e.g. CircleCI)

### ISSUE THREAD

**Issue by gonewest818** [undercover-el/undercover.el#38]
The code that assumes Travis CI could be generalized to support also CircleCI, if not other CI services too.

**Comment by sviridov** [comment]
Hi @gonewest818,

Support for other CI services is currently implemented via [COVERALLS_REPO_TOKEN](https://github.com/sviridov/undercover.el#configuration) environment variable.

Or are you talking about some meta information that can be obtained in other CI environments?

**Comment by gonewest818** [comment]
Consider this a companion to #34. Putting the two tickets together would read like: "Generalize undercover to pave the way for alternate coverage report formats, uploaded to other coverage reporting services, while running in other CI services."

**Comment by xendk** [comment]
Well, looks like there's at least some support for Shippable.

But wrt #34, there's not much support needed as the Codecov bash script itself supports a dizzying amount of CI services. All undercover really needs to figure out is whether its running under CI to determine if coverage should be collected.

**Comment by CyberShadow** [comment]
To an extent, e2101df0c907f3ee8d8cbe331d77230561cb4868 moves a bit in that direction, with 5611a752f94c794855aa25bda946b5c92c5f584c being an addition making use of the same pattern. However, those changes occurred in code specifically handling Coveralls. There is still currently an M&times;N design problem between the CI service we're running under and the coverage service that we're uploading to, which will need to be fixed to enable more/better support for coverage services.

**Comment by CyberShadow** [comment]
Thoroughly fixed in b41937363ccef04799928da05927a38f2fc3c470.

**Comment by gonewest818** [comment]
Thanks!
