### ISSUE TITLE
Create a release

### ISSUE THREAD

**Issue by doublep** [undercover-el/undercover.el#55]
Since `undercover` is available from Melpa.Stable, one would expect it to be more-or-less up-to-date, minus the unstabilized features, of course. However, the latest stable release is now three years old.

Please add 0.6.2 or 0.7 tag.

**Comment by CyberShadow** [comment]
Thanks for the suggestion.

Pushed tag v0.7.0.

**Comment by CyberShadow** [comment]
BTW, sorry for not responding more promptly, somehow I ended up not being subscribed to this repository, so I had no idea about all the developments happening here.

**Comment by doublep** [comment]
No problem. There are quite a few PR/issues from me because I was integrating `undercover` with [Eldev](https://github.com/doublep/eldev), which is a relatively new build tool somewhat similar to Cask. Would you accept a PR to document usage in your `README`? This is documented in Eldev's `README` already, but I wasn't creating a PR for `undercover.el` since it frankly looked pointless at the time.

**Comment by CyberShadow** [comment]
> Would you accept a PR to document usage in your `README`?

Sure!
