### ISSUE TITLE
Invalid function: edebug-after 0 1

### ISSUE THREAD

**Issue by tseenshe** [undercover-el/undercover.el#59]
I would like to use undercover in my project https://gitlab.com/tseenshe/haskell-tng.el

However, when I follow the instructions and run

```
UNDERCOVER_FORCE=true cask exec ert-runner
```

I get

```
Invalid function: (edebug-after 0 1 haskell-tng--layout-at-point)
```

and no further output.

I can only minimise to running the test containing that function

```
UNDERCOVER_FORCE=true cask exec ert-runner test/haskell-tng-layout-test.el
```

I followed these instructions, which I found when reading the undercover source code

```
  (message "UNDERCOVER: 2. Run M-: `%s';" "(require 'edebug)")
  (message "UNDERCOVER: 3. Run M-x `edebug-all-defs';")
  (message "UNDERCOVER: 4. Run M-x `toggle-debug-on-error'.")
  (message "UNDERCOVER: 5. Run M-x `eval-buffer';")
```

but I do not get any error when I eval-buffer on the file containing that function. So I do not know how to proceed.

**Comment by doublep** [comment]
Can you test if [this change](https://github.com/undercover-el/undercover.el/pull/57) fixes the bug?

**Comment by CyberShadow** [comment]
Please leave a comment if this problem is still reproducible.
