### ISSUE TITLE
Support for github actions.

### ISSUE THREAD

**Issue by Ergus** [undercover-el/undercover.el#64]
Hi:

I am trying to port my travis tests to github actions. But I get this error everytime the tests start:

![image](https://user-images.githubusercontent.com/6975176/101262551-fb172f00-373f-11eb-83ac-a9f8d0ed2882.png)

The cask file is an standard one:

```
(source gnu)
(source melpa)

(package-file "composable.el")

(development
 (depends-on "ecukes")
 (depends-on "espuds")
 (depends-on "ert-runner")
 (depends-on "el-mock")
 (depends-on "undercover"))
```

And the error does not happen when using emacs 26...

Any help?

Thanks in advance,
Ergus

**Comment by CyberShadow** [comment]
The issue you described looks like a problem with Cask, if anything.

In any case, I added support for reading Github Actions' environment variables, and documented how to set it up (with Coveralls).

In action:
- https://github.com/Emacs-D-Mode-Maintainers/Emacs-D-Mode/actions
- https://coveralls.io/github/Emacs-D-Mode-Maintainers/Emacs-D-Mode?branch=master
