### ISSUE TITLE
Support for LCOV output

### ISSUE THREAD

**Issue by jinnovation** [undercover-el/undercover.el#68]
It would be nice to have the option to output the coverage report as LCOV. This would allow for compatibility with [Coveralls' own GitHub Action](https://github.com/marketplace/actions/coveralls-github-action), which would allow for native reporting of test coverage in the PR itself.

**Comment by CyberShadow** [comment]
Is there a description of this format somewhere?

**Comment by jinnovation** [comment]
There's a general description of the expected format [here](http://ltp.sourceforge.net/coverage/lcov/geninfo.1.php).

There's also some related discussion in nedbat/coveragepy#587 that might be useful.

**Comment by CyberShadow** [comment]
Do you know if it's sufficient to emit only `SF:`, `DA:`, `LH:`, and `LF:` lines for Coveralls?

**Comment by CyberShadow** [comment]
[Seems to work](https://github.com/undercover-el/undercover.el-github-coveralls-integration-example), can you try it?

In `Cask`:

```emacs-lisp
(development
 ...
 (depends-on "undercover"
             :git "https://github.com/undercover-el/undercover.el"
             :branch "next"))
```

And then [as described here](https://github.com/undercover-el/undercover.el/tree/next#github-actions--coveralls--coveralls-github-action).

**Comment by CyberShadow** [comment]
Thanks for testing, that problem should now be fixed.

**Comment by jinnovation** [comment]
Excellent, [looks like that did the trick](https://github.com/jinnovation/kubernetes-el/pull/3).

Let me know how else I can assist.

**Comment by CyberShadow** [comment]
If everything looks good to you so far, let me know and I'll push to master and tag a release.

**Comment by jinnovation** [comment]
Looks good to me—doesn't look like there's anything out of the ordinary in the reporting in Coveralls for my repo.

I'm not in a position to comment on the undercover.el implementation itself, so I'll happily defer to you on that.

Looking forward to the release. Thanks again for looking into this.

**Comment by CyberShadow** [comment]
OK, here it is: https://github.com/undercover-el/undercover.el/releases/tag/v0.8.1

> Thanks again for looking into this.

Your appreciation is appreciated :)

**Comment by jinnovation** [comment]
> OK, here it is: https://github.com/undercover-el/undercover.el/releases/tag/v0.8.1

Awesome, I think we can close this issue now. 👏
