### ISSUE TITLE
Uncommon ELisp project structure

### ISSUE THREAD

**Issue by kostafey** [undercover-el/undercover.el#70]
Could you please add support for uncommon ELisp project structure, e.g. if *.el source code files located not in root directory but in `src` one?

**Comment by CyberShadow** [comment]
Does that not already work? In the README there is this example:

```elisp
(undercover "*.el" "awesome-extensions/*.el" (:exclude "awesome-examples.el"))
```

so I think you could indicate `"src/*.el"` there?

**Comment by kostafey** [comment]
Yes exactly. Thank you.
